### ISSUE TITLE
Demo code.

### ISSUE THREAD

**Issue by FGMGIT** [frontyard/cordova-plugin-exoplayer#2]
**There is any way to see any implementation demo code?**

I'm working in a version for Android TV platform. The controls are working properly with remote control keys but they are not working when control panel is hide, and not able to show the control panel by pressing remote control keys. I would like also to control the amount of seconds of the back and forward buttons.

Any help or orientation will be helpful.

Thank you.
FGM

**Comment by frontyard** [comment]
Default controls in ExoPlayer are not that great and not easily configurable unless you want to mess with a lot of Java/XML. What we are aiming for with this plugin is complete control of the player from Cordova which you can do right now since event are communicated to your Cordova app.

We are also thinking about adding simple info popup to the plugin that could be used to communicate to the user what event your app is handling (like play/pause, forward/rewind, etc).

**Comment by FGMGIT** [comment]
Hi thank you for the answer. For the moment I was trying to handle any Key Event to show the control in the same way you are doing with Touch Events, but no results for the moment. I found the control navigation with remote key are working while the 5 sec. is active, but after that period I'm not able to handle any Key Event to active again the control panel.

**Comment by FGMGIT** [comment]
Hi @frontyard,

I forked the repo and added the method to handle any key event to show the controls and now its working properly in TV platform.

**Comment by frontyard** [comment]
Thanks! Please create a pull request.

**Comment by casic** [comment]
Can you make  ExoPlayer  in new Activity instead Dialog ?  Or   with  Surface view it  rect params in  JS

**Comment by frontyard** [comment]
@casic You feature request is not related to this thread. If you want to start a new thread we can continue the conversation there.

**Comment by mkalyon** [comment]
How can send olaylist like that,
{
"url":"url1",
"name":"name1",
"logo":"logo1"
.......
},
......
If not, can u add playlist support.

**Comment by frontyard** [comment]
@mkalyon Please open a new issue with your feature request.
