### ISSUE TITLE
HTML overlay layer ?

### ISSUE THREAD

**Issue by scramatte** [frontyard/cordova-plugin-exoplayer#26]
Does it posible to have HTML overlay  layer over exoplayer playback  ?
For example to show menu or EPG data.

**Comment by frontyard** [comment]
Currently it is not. What would really be the ultimate solution is for plugin not to have any UI but let Cordova app overlay whatever UI it wants. This however is not a trivial change and it would require changing the plugin from using Dialog to something else like Fragment while keeping compatibility with older versions of Android.

If anyone wants to take this work on, it would be tremendous help.

**Comment by scramatte** [comment]
Take a look to following product to pickup some ideas (they have cordova plugin too)
http://veeplay.com/

**Comment by devcer** [comment]
I was trying to add a skip button overlay on full screen exoplayer but couldn't do it. For HTML5 video if i set the z-index of the button element to 2147483647 then it overlays the video but the same solution doesn't work for layover on exoplayer.

**Comment by frontyard** [comment]
This is a bit complicated. Because plugin is not part of Cordova app in a sense that it participates in DOM construction, setting z-index has no effect on it. In other words this plugin takes over the display. There are ways to make this happen as discussed in other threads, for example by changing the plugin from using Dialog to using Fragment and then setting Cordova app to show above the plugin. With some transparency in the Cordova app, the effect would be the same.

This however is not a trivial change and I haven't had time nor need for it yet.
