### ISSUE TITLE
Video with specific height and width

### ISSUE THREAD

**Issue by hadiarakos** [frontyard/cordova-plugin-exoplayer#38]
Hello. 
Is it possible to use the exoplayer as an element in html (Or to )? 
I created a cordova app and for now I am using video html tag to play inline video with specific height and width.

Thank you. 

 
![cordovaappscreenshot](https://user-images.githubusercontent.com/16122234/30001287-14d2cc36-9092-11e7-9eed-87006ce985c1.jpg)

**Comment by frontyard** [comment]
Yes, but it's not advertised yes as it has some issues.

If you pass in `dimensions` config element the player window should be scaled down and positioned accordingly:
`dimensions: {
  x: 100,
  y: 100,
  width: 320,
  height: 240
}`

However due to browser and underlaying os having different display metrics this hasn't been pixel perfect so far.

If you try it let me know if it works for you.

**Comment by hadiarakos** [comment]
Hello, 
Thank you for your email. 
I will try it and I will let you know. 

———
Regards
Thales P. Hadiarakos

On 4 September 2017 at 11:25:34, Nedim Cholich (notifications@github.com) wrote:

Yes, but it's not advertised yes as it has some issues.

If you pass in dimensions config element the player window should be scaled down and positioned accordingly:
dimensions: { x: 100, y: 100, width: 320, height: 240 }

However due to browser and underlaying os having different display metrics this hasn't been pixel perfect so far.

If you try it let me know if it works for you.
