### ISSUE TITLE
Suggestion Header

### ISSUE THREAD

**Issue by Wannerron** [frontyard/cordova-plugin-exoplayer#51]
Could you add a Custom Header option?

**Comment by frontyard** [comment]
It's possible.

We'd need to add new parameter to the plugin for custom headers. We'd need custom HttpDataSource.Factory that allows setting headers since default one doesn't. Then we'd need to use that custom factory in Player#getMediaSource passing it any custom headers from Cordova app.

Care to implement and send a PR?

**Comment by Wannerron** [comment]
Yes, I would be extremely grateful.

**Comment by frontyard** [comment]
@Wannerron Hehe, what I meant is do you care to implement it and send me a PR?

**Comment by Wannerron** [comment]
I'm sorry, I'm using the translate and I'm not I understand what you're talking about. I wanted to add a custom referer. Thank you

**Comment by Wannerron** [comment]
I got it now, thank you.
