### ISSUE TITLE
Cordova video plugin with looping control?

### ISSUE THREAD

**Issue by BobAchgill** [frontyard/cordova-plugin-exoplayer#62]
What video plugin can I add to my project that will have a looping control button when exercising a link to a local video?

Is this it?!

**Comment by frontyard** [comment]
@BobAchgill This plugin allows playing video/audio streams and files in Cordova/PhoneGap/Ionic apps using Google's ExoPlayer. The UI that plugin provides is minimal and it includes few controls (play/pause, rewind, forward) and info bar. All UI controls are optional. It does not have looping control.

It's possible to add it since ExoPlayer has added that functionality, but.. the plugin would need to be upgraded to the latest version of ExoPlayer, AND new code would have to be written to allow enabling the button. The second part requires time so if you want to fork the project and contribute, that would be awesome!

**Comment by BobAchgill** [comment]
Is there demo code showing use of a playlist for the ExoPlayer plugin? Tks!
I'm not a developer.

**Comment by frontyard** [comment]
@BobAchgill If you are not a developer this project might not be for you. It's intended to be part of a larger app, on it's own it doesn't do anything.

**Comment by BobAchgill** [comment]
Are the functions playlist and subtitling available for programming in the Cordova plugin version of ExoPlayer?

**Comment by frontyard** [comment]
You would manage playlists in Cordova app, that is out of the scope of this plug-in.Then your app would send each URL to the plug-in to play.

**Comment by frontyard** [comment]
Subtitles are supported. Read the readme.
