### ISSUE TITLE
Anyway we could modify it to just have a transparent background and allow to see through to what is in the background when video is not playing?

### ISSUE THREAD

**Issue by jfrux** [frontyard/cordova-plugin-exoplayer#72]

**Comment by frontyard** [comment]
If I understand you question correctly, you're suppose to close the player when you're not using it which releases its UI and shows your Cordova app.

**Comment by jfrux** [comment]
Thanks! Actually I’m wanting to show my own loading UI between playback of each video in a playlist that I already have built.

**Comment by frontyard** [comment]
It's a bit more complicated than that. What you're referring to as loading is buffering and can happen at any point not just when you start the playback. So the only way to do what you're suggesting would be to layer Cordova on top of the plugin, which currently is not possible due to plugin's usage of Dialog as the main container.

You could fork the plugin and customize the UI to suit your needs.

**Comment by frontyard** [comment]
Also, I'm not sure I understand a bit about transparency? Are you suggesting plugin be transparent?

**Comment by jfrux** [comment]
Ya I probably just don’t understand the complexity of it.  Definitely sounds like I’m over simplifying it.

I meant like have no background on the dialog and show the Cordova app through the black bg of the dialog.  So just allow the bg to be transparent to see the app behind it?  I have state of existing HTML5 players in the bg which I’m swapping for this for certain platforms.

Currently my app supports 10+ different environments and was looking for this player to solve some performance issues on androidtv / firetv.

I have it working but UX is suffering.

Thanks for your input!

**Comment by jfrux** [comment]
Got it.  Kind of defeats the purpose of cordova at this point I suppose.  Guess I’ll stick with HTML5 which keeps things more cross platform.

Thanks again for the info!  Appreciate it!

**Comment by frontyard** [comment]
Well no, not really. Cordova is excellent at keeping the UI consistent across all platforms it supports and the whole write once run anywhere. But it's horrendous at playing HLS or DASH. That's why we still need this plugin. I would love to be able to get rid of it, but unfortunately we're not there yet.
